name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python -m pip install -U pip
      - run: pip install -e ".[dev]"
      - run: ruff check src
      - run: pytest --maxfail=1 --disable-warnings -q
      - run: python -m build
